[    
  OK     
] Reached target Basic System.  
         Starting System Logging Service...  
         Starting Terminate Plymouth Boot Screen...  
         Starting Wait for Plymouth Boot Screen to Quit...  
         Starting Network Manager...  
 %G 
  
  [?1l >  
  
     
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
  
 
   
[anaconda] 1:main* 2:shell  3:log  4:storage-log  5:program-log                   
       
      
  
      
Starting installer, one moment...      
  
 
      
  
 
anaconda 20.25.15-1 for Fedora 20 started.      
  
   
      
  
   
07:07:45 Running pre-installation scripts      
  
   
+ wget -O - http://lab-devel-02.beaker.example.com:8000/install_start/4731
--2014-01-15 07:07:45--  http://lab-devel-02.beaker.example.com:8000/install_start/4731
Resolving lab-devel-02.beaker.example.com (lab-devel-02.beaker.example.com)... 2620:52:0:1040:5054:ff:fe12:78c3, 10.16.64.10
Connecting to lab-devel-02.beaker.example.com (lab-devel-02.beaker.example.com)|2620:52:0:1040:5054:ff:fe12:78c3|:8000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4 [text/plain]
Saving to: 'STDOUT'
True
     0K                                                       100%  786K=0s

2014-01-15 07:07:45 (786 KB/s) - written to stdout [4/4]

+ wget -O /tmp/anamon http://lab-devel-02.beaker.example.com/beaker/anamon
--2014-01-15 07:07:45--  http://lab-devel-02.beaker.example.com/beaker/anamon
Resolving lab-devel-02.beaker.example.com (lab-devel-02.beaker.example.com)... 2620:52:0:1040:5054:ff:fe12:78c3, 10.16.64.10
Connecting to lab-devel-02.beaker.example.com (lab-devel-02.beaker.example.com)|2620:52:0:1040:5054:ff:fe12:78c3|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8771 (8.6K) [text/plain]
Saving to: '/tmp/anamon'

     0K ........                                              100% 8.81M=0.001s

2014-01-15 07:07:45 (8.81 MB/s) - '/tmp/anamon' saved [8771/8771]

+ python /tmp/anamon --recipe-id 4731 --xmlrpc-url http://lab-devel-02.beaker.example.com:8000/RPC2
      
  
   
07:07:46 Not asking for VNC because of an automated install      
  
   
      
  
   
07:07:46 Not asking for VNC because text mode was explicitly asked for in kickstart      
  
   
      
  
   
Starting automated install      
  
      
      
  
      
.      
  
      
      
  
      
.      
  
      
      
  
      
.      
  
      
      
  
      
.      
  
      
      
  
      
.      
  
      
      
  
      
.      
  
      
      
  
      
.      
  
      
      
  
      
.      
  
      
      
  
      
.      
  
      
      
  
      
.      
  
      
      
  
      
.      
  
      
      
  
      
.      
  
      
      
  
      
.      
  
      
      
  
      
.      
  
      
 
      
  
   
Generating updated storage configuration      
  
   
      
  
   
error: XDG_RUNTIME_DIR not set in the environment.      
  
   
      
  
   
Unable to init server      
  
    
      
  
    
error: XDG_RUNTIME_DIR not set in the environment.      
  
    
      
  
    
Unable to init server      
  
      
      
  
      
An unknown error has occured, look at the /tmp/anaconda-tb* file(s) for more details      
  
      
 
      
  
      
===============================================================================      
  
      
      
  
      
An unknown error has occurred 
=============================================================================== 
anaconda 20.25.15-1 exception report 
Traceback (most recent call first): 
  File "/usr/lib/python2.7/site-packages/blivet/partitioning.py", line 822, in doPartitioning 
    "maxSize": part.format.maxSize}) 
  File "/usr/lib64/python2.7/site-packages/pyanaconda/kickstart.py", line 890, in execute 
    doPartitioning(storage) 
  File "/usr/lib64/python2.7/site-packages/pyanaconda/kickstart.py", line 1747, in doKickstartStorage 
    ksdata.partition.execute(storage, ksdata, instClass) 
  File "/usr/lib64/python2.7/site-packages/pyanaconda/ui/tui/spokes/storage.py", line 260, in execute 
    doKickstartStorage(self.storage, self.data, self.instclass) 
  File "/usr/lib64/python2.7/site-packages/pyanaconda/ui/tui/hubs/summary.py", line 51, in setup 
    spoke.execute() 
  File "/usr/lib64/python2.7/site-packages/pyanaconda/ui/tui/__init__.py", line 166, in setup 
    should_schedule = obj.setup(self.ENVIRONMENT) 
  File "/sbin/anaconda", line 1118, in <module> 
      
  
      
      
  
      
    anaconda._intf.setup(ksdata) 
TypeError: %d format: a number is required, not NoneType 

What do you want to do now? 
1) Report Bug 
2) Debug 
3) Run shell 
4) Quit 

      
  
      
      
  
      
Please make your choice from above:       
  
       
[-- MARK -- Wed Jan 15 07:10:00 2014] 
[-- MARK -- Wed Jan 15 07:15:00 2014] 
